apiVersion: v1
kind: ConfigMap
metadata:
  name: opsacademy-config
  namespace: opsacademy
data:
  PORT: "4000"
  AI_HUB_PORT: "5000"
  SANDBOX_MODE: "pty"
  AI_HUB_URL: "http://opsacademy-ai-hub.opsacademy.svc.cluster.local:5000"
  CLIENT_URL: "https://opsacademy.dev"
